### ISSUE TITLE
ERB Linting doesn't work correctly

### ISSUE THREAD

**Issue by Amaljith-K** [bigbinary/wheel#958] opened 2023-03-07 07:48 UTC
ERB Linting doesn't throw errors for 
```html.erb
<script></script>
<script>
  NeetoChat.identity={ "email":"<%= current_user.email %>" };
</script>
```

But it does for:
```html.erb
<script>
  NeetoChat.identity={ "email":"<%= current_user.email %>" };
</script>
```

errors:
```
app/views/shared/_neeto_replay.html.erb:2:32: erb interpolation in javascript tag must call '(...).to_json'
1 error(s) were found in ERB files
```

@yedhink _a
cc @vishal24367

**Comment by yedhink** [comment] 2023-03-07 08:03
@udai1931 _a Please take a look into this.

@Amaljith-K Can you please point out the repo/PR in which this issue was discovered?

**Comment by Amaljith-K** [comment] 2023-03-07 08:08
All PRs were failing till the main branch was updated in neeto-invoice.
The failing commit: https://github.com/bigbinary/neeto-invoice-web/tree/8833ae8ed414364c5795063ce0a88961b73e6f7a

**Comment by sumanranjanpanda** [comment] 2023-05-17 07:26
Is it fixed now?

**Comment by yedhink** [comment] 2023-05-17 07:42
This was fixed in the host repo when I discussed with Vishal back then. Closing this. Reopen if the issue is still being faced.

**Closed by yedhink** 2023-05-17 07:42 UTC
