### ISSUE TITLE
Add a test for autoloading in staging env in circle ci

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [bigbinary/wheel#198] opened 2018-09-07 08:25 UTC
This will prevent issues related to autoloading issues which are generally not caught in development.

**Comment by vipulnsward** [comment] 2018-10-09 09:34
In one of the projects, we do "eager" load instead of autoload on test env. This ensures, the issue is caught on test instead of staging/production. The cost to eager load whole App, should be minimal.

**Comment by prathamesh-sonpatki** [comment] 2018-10-18 13:54
Eager loading is fine as well.

**Comment by neerajdotname** [comment] 2018-12-21 17:57
Heroku runs in staging or Heroku env which is a copy of `production.rb`. 

I do not think circle ci which primarily runs unit tests is the right place to try to catch bugs related to autoloading. 

Closing this issue. Please reopen with more details about what the implementation might look like.

**Closed by neerajdotname** 2018-12-21 17:57 UTC
